{
    users:[
        {
            email:'',
            gender:'',

            verified:true,
            ktp:'',
            role:'user',
            kategori:[
                '','',''
            ],
            
        }
    ];

    promotor:[
        {
            namaPromotor:'',
            alamatPromotr:'',
            verified:true,

        }
    ];
    acara:[
        {
            id:0,
            nama:"event",
            harga:"",
            tanggalMulai:'19911111111',
            tanggalAkhir:'19999111111',
            kategori:[
                '','',''
            ],
            like:0,
            unlike:0,
            penonton:0,
            pendaftar:0,
            deskripsi:'',
            banner:'',

        }
    ];
    komentar:[
        'idacara'=[
            {
                idkomen:'',
                iduser:'',
                pesan:''
            },
            {
                idkomen:'',
                iduser:'',
                pesan:''
            },
            {
                idkomen:'',
                iduser:'',
                pesan:''
            },
        ]
    ];
    kategori:[
        {
            nama:''
        }
    ];
    tiket:[
        {
            id:0,
            idAcara:0,
            iduser:0
        }
    ]

}